"""
Django settings for suv_kerak project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

import os
try:
    from dotenv import load_dotenv  # pip install python-dotenv
    load_dotenv()
except Exception:
    pass
from django.db import models
from django.utils import timezone

TELEGRAM_BOT_TOKEN = os.getenv("BOT_TOKEN", "")
BACKEND_BASE_URL = os.getenv("WEBHOOK_HOST", "")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# .env ни локалда юклаймиз (Heroku’да бу файл йўқ)
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-only-insecure-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

TIME_ZONE = os.environ.get("TZ", "Asia/Tashkent")

# settings.py
ALLOWED_HOSTS = [
    "suv-kerak-backend-eu-d9af752240af.herokuapp.com",  # ✅ протоколсиз
    ".herokuapp.com",                                   # ✅ heroku сабдоменлари
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app"
]


AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 🔽 Қўшимча иловалар
    'accounts',
    'agents',
    'couriers',
    'orders',
    'finance',
    'bots.apps.BotsConfig', # suv_kerak боти
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        # сизда бор форматтер
        "jsonline": {"format": "%(message)s"},
        # оддий формат ҳам керак бўлса
        "simple": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
    },

    "handlers": {
        # консоль — encoding қўйилмайди
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "jsonline",  # ёки "simple"
            "level": "INFO",
        },
        # файл — мана шу ерда encoding берилади
        "bot_file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "bot.log",
            "formatter": "simple",
            "level": "INFO",
            "encoding": "utf-8",      # ✅ тўғри жой
        },
    },

    "loggers": {
        # 👉 бот/вебхук логлари шу ерга тушади
        "bots": {
            "handlers": ["console", "bot_file"],   # консоль ва файлга ёзсин
            "level": "INFO",
            "propagate": False,
        },

        # қолганлар (ихтиёрий)
        "aiogram":           {"handlers": ["console"], "level": "INFO", "propagate": False},
        "aiogram.dispatcher":{"handlers": ["console"], "level": "INFO", "propagate": False},
        "django.request":    {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },

    # root каттиқ бўлмасин
    "root": {"handlers": ["console"], "level": "ERROR"},
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "suv_kerak.middleware.AccessLogMiddleware",
]


try:
    import argon2  # noqa
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.Argon2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
    ]
except ImportError:
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
        "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
        "django.contrib.auth.hashers.ScryptPasswordHasher",
    ]



ROOT_URLCONF = 'suv_kerak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "suv_kerak" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suv_kerak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# ---- DB: локалда SQLite, Heroku’да Postgres ----
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
if os.getenv("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.config(conn_max_age=600, ssl_require=True)



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

USE_I18N = True
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

# (ихтиёрий) Келажакда тил алмаштиришни осонлаштириш учун рўйхат
LANGUAGES = [
    ("uz-Cyrl", "Ўзбек (Кирилл)"),
    ("ru", "Русский"),
    ("uz-Latn", "Oʻzbek (Lotin)"),
    ("en", "English"),    
]


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
