# Generated by Django 5.2.4 on 2025-09-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_rename_promkod_userboss_agent_promkod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('agent_id', models.BigIntegerField(unique=True)),
                ('agent_name', models.CharField(max_length=55)),
                ('agent_promkod', models.TextField(blank=True, null=True)),
                ('business_map', models.JSONField(blank=True, default=list)),
                ('boss_name', models.CharField(blank=True, max_length=55, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Сотув агенти',
                'verbose_name_plural': 'Сотув агентлари',
                'db_table': 'agent_account',
                'indexes': [models.Index(fields=['agent_id'], name='idx_agent_agent_id'), models.Index(fields=['status'], name='idx_agent_status')],
            },
        ),
    ]
