# Generated by Django 5.2.4 on 2025-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agentaccount',
            name='pin_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
