# Generated by Django 5.2.4 on 2025-09-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentaccount_password_agentaccount_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentaccount',
            old_name='boss_name',
            new_name='business_name',
        ),
    ]
