# Generated by Django 5.2.4 on 2025-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBoss',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('boss_id', models.BigIntegerField()),
                ('boss_name', models.CharField(max_length=55)),
                ('client_tg_id', models.BigIntegerField()),
                ('client_tel_num', models.CharField(max_length=15)),
                ('buyurtma_num', models.BigIntegerField()),
                ('kuryer_id', models.BigIntegerField()),
                ('kuryer_name', models.CharField(max_length=55)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_operation', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('cash_message', models.CharField(blank=True, max_length=255)),
                ('grated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Boss Kassa',
                'verbose_name_plural': 'Boss Kassalari',
                'db_table': 'cash_boss',
                'indexes': [models.Index(fields=['boss_id'], name='idx_cashboss_boss'), models.Index(fields=['client_tel_num'], name='idx_cashboss_client_tel'), models.Index(fields=['kuryer_id'], name='idx_cashboss_kuryer')],
            },
        ),
    ]
