# Generated by Django 5.2.5 on 2025-09-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_business_userboss_boss_tel_num_user_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('boss_id', models.BigIntegerField()),
                ('boss_name', models.CharField(max_length=55)),
                ('client_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('client_tel_num', models.CharField(blank=True, max_length=15, null=True)),
                ('buyurtma_num', models.BigIntegerField(blank=True, null=True)),
                ('kuryer_id', models.BigIntegerField()),
                ('kuryer_name', models.CharField(max_length=55)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_operation', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('cash_message', models.CharField(blank=True, max_length=255)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
            ],
            options={
                'db_table': 'cash_boss',
            },
        ),
        migrations.CreateModel(
            name='CashKuryer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('boss_id', models.BigIntegerField()),
                ('boss_name', models.CharField(max_length=55)),
                ('client_tg_id', models.BigIntegerField()),
                ('client_tel_num', models.CharField(max_length=15)),
                ('buyurtma_num', models.BigIntegerField()),
                ('kuryer_id', models.BigIntegerField()),
                ('kuryer_name', models.CharField(max_length=55)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_operation', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('status', models.CharField(choices=[('buffer', 'Buffer'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='buffer', max_length=16)),
                ('grated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kuryer Kassa',
                'verbose_name_plural': 'Kuryer Kassalari',
                'db_table': 'cash_kuryer',
                'indexes': [models.Index(fields=['boss_id'], name='idx_ck_boss'), models.Index(fields=['kuryer_id'], name='idx_ck_kuryer'), models.Index(fields=['client_tel_num'], name='idx_ck_client_tel'), models.Index(fields=['buyurtma_num'], name='idx_ck_buyurtma'), models.Index(fields=['status'], name='idx_ck_status')],
            },
        ),
        migrations.CreateModel(
            name='CashState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('boss_id', models.BigIntegerField()),
                ('boss_name', models.CharField(max_length=55)),
                ('kuryer_id', models.BigIntegerField()),
                ('kuryer_name', models.CharField(max_length=55)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Тасдиқ пайтида ҳисобланади', max_digits=14)),
                ('cash_operation', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('tasdiq_vaqti', models.DateTimeField(blank=True, null=True)),
                ('rad_vaqti', models.DateTimeField(blank=True, null=True)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
                ('cash_boss', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_state', to='finance.cashboss')),
            ],
            options={
                'db_table': 'cash_state',
            },
        ),
        migrations.CreateModel(
            name='CourierWaterBottleBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('boss_id', models.BigIntegerField()),
                ('boss_name', models.CharField(max_length=55)),
                ('client_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('client_tel_num', models.CharField(blank=True, max_length=15, null=True)),
                ('buyurtma_num', models.BigIntegerField(blank=True, null=True)),
                ('kuryer_id', models.BigIntegerField()),
                ('kuryer_name', models.CharField(max_length=55)),
                ('income', models.PositiveIntegerField(default=0)),
                ('expense', models.PositiveIntegerField(default=0)),
                ('operation', models.CharField(choices=[('in_from_boss', 'In from Boss'), ('sell_to_client', 'Sell to Client'), ('return_empty', 'Return Empty'), ('adjustment', 'Adjustment')], max_length=20)),
                ('water_balance', models.PositiveIntegerField(default=0)),
                ('bottle_balance', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('draft', 'Draft'), ('void', 'Void')], default='ok', max_length=10)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
            ],
            options={
                'verbose_name': 'Kuryer Water/Bottle Balance',
                'verbose_name_plural': 'Kuryer Water/Bottle Balances',
                'db_table': 'kuryer_water_bottle_balance',
            },
        ),
        migrations.AddIndex(
            model_name='cashboss',
            index=models.Index(fields=['business', 'boss_id'], name='cash_boss_busines_142693_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboss',
            index=models.Index(fields=['business', 'kuryer_id'], name='cash_boss_busines_8cd64f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashstate',
            index=models.Index(fields=['business', 'boss_id', 'status'], name='cash_state_busines_89fbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashstate',
            index=models.Index(fields=['business', 'kuryer_id', 'status'], name='cash_state_busines_fe8517_idx'),
        ),
        migrations.AddIndex(
            model_name='courierwaterbottlebalance',
            index=models.Index(fields=['business', 'kuryer_id', 'sana', 'vaqt'], name='idx_kwbb_kur_dt'),
        ),
        migrations.AddIndex(
            model_name='courierwaterbottlebalance',
            index=models.Index(fields=['business', 'boss_id'], name='idx_kwbb_boss'),
        ),
        migrations.AddIndex(
            model_name='courierwaterbottlebalance',
            index=models.Index(fields=['business', 'operation'], name='idx_kwbb_op'),
        ),
    ]
