# Generated by Django 5.2.5 on 2025-09-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_userboss_boss_tel_num_user_business'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossSystemAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('operation', models.CharField(choices=[('income', 'Income (Top-up)'), ('expense', 'Expense (Water Sale)'), ('promo', 'Promo/Free')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
            ],
            options={
                'verbose_name': 'Boss System Account',
                'verbose_name_plural': 'Boss System Accounts',
                'db_table': 'boss_system_account',
                'indexes': [models.Index(fields=['business', 'sana'], name='idx_bsa_biz_sana'), models.Index(fields=['business', 'operation'], name='idx_bsa_biz_op')],
            },
        ),
    ]
