# Generated by Django 5.2.5 on 2025-09-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bosssystemaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bosssystemaccount',
            options={'verbose_name': 'Тизим ҳисоби', 'verbose_name_plural': 'Тизим ҳисоби'},
        ),
    ]
