# Generated by Django 5.2.5 on 2025-09-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bosssystemaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashboss',
            options={'verbose_name': 'Босс касса ҳисоби', 'verbose_name_plural': 'Босс касса ҳисоби'},
        ),
        migrations.AlterModelOptions(
            name='cashkuryer',
            options={'verbose_name': 'Курер касса ҳисоби', 'verbose_name_plural': 'Курер касса ҳисоби'},
        ),
        migrations.AlterModelOptions(
            name='cashstate',
            options={'verbose_name': 'Касса ҳолати', 'verbose_name_plural': 'Касса ҳолати'},
        ),
        migrations.AlterModelOptions(
            name='courierwaterbottlebalance',
            options={'verbose_name': 'Курер сув ва тара ҳисоби', 'verbose_name_plural': 'Курер сув ва тара ҳисоби'},
        ),
    ]
