# Generated by Django 5.2.4 on 2025-09-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_promkod_userboss_agent_promkod_and_more'),
        ('finance', '0004_alter_cashboss_options_alter_cashkuryer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Асосий нарх', max_length=60)),
                ('period', models.CharField(choices=[('month', 'Ой'), ('year', 'Йил')], default='month', max_length=8)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_plans', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Сув нарх режаси',
                'verbose_name_plural': 'Сув нарх режалари',
                'db_table': 'water_price_plan',
            },
        ),
        migrations.CreateModel(
            name='WaterPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField(default=0)),
                ('max_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='finance.waterpriceplan')),
            ],
            options={
                'verbose_name': 'Сув нарх диапазони',
                'verbose_name_plural': 'Сув нарх диапазонлари',
                'db_table': 'water_price_tier',
                'ordering': ['priority', 'min_qty'],
            },
        ),
        migrations.AddIndex(
            model_name='waterpriceplan',
            index=models.Index(fields=['business', 'is_active'], name='water_price_busines_971bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='waterpriceplan',
            index=models.Index(fields=['business', 'period'], name='water_price_busines_c51cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='waterpricetier',
            index=models.Index(fields=['plan', 'is_active'], name='water_price_plan_id_99babc_idx'),
        ),
        migrations.AddIndex(
            model_name='waterpricetier',
            index=models.Index(fields=['plan', 'min_qty', 'max_qty'], name='water_price_plan_id_3df0bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterpricetier',
            constraint=models.CheckConstraint(condition=models.Q(('max_qty__isnull', True), ('max_qty__gte', models.F('min_qty')), _connector='OR'), name='tier_min_lte_max'),
        ),
    ]
