# Generated by Django 5.2.4 on 2025-09-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userboss_agent_name_and_more'),
        ('finance', '0005_waterpriceplan_waterpricetier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashkuryer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.business'),
        ),
    ]
