# Generated by Django 5.2.4 on 2025-09-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_cashkuryer_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bosssystemaccount',
            options={'verbose_name': 'Бизнес ва тизим ҳисоби', 'verbose_name_plural': 'Бизнес ва тизим ҳисоби'},
        ),
        migrations.AlterModelTable(
            name='bosssystemaccount',
            table='business_system_account',
        ),
    ]
