# Generated by Django 5.2.4 on 2025-09-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userboss_agent_name_and_more'),
        ('finance', '0007_alter_bosssystemaccount_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BossSystemAccount',
            new_name='BusinessSystemAccount',
        ),
        migrations.RemoveField(
            model_name='waterpricetier',
            name='plan',
        ),
        migrations.DeleteModel(
            name='WaterPricePlan',
        ),
        migrations.DeleteModel(
            name='WaterPriceTier',
        ),
    ]
