# Generated by Django 5.2.4 on 2025-09-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermenedjer_delete_userboss_and_more'),
        ('finance', '0008_rename_bosssystemaccount_businesssystemaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMenedjer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('menedjer_id', models.BigIntegerField()),
                ('menedjer_name', models.CharField(max_length=55)),
                ('client_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('client_tel_num', models.CharField(blank=True, max_length=15, null=True)),
                ('buyurtma_num', models.BigIntegerField(blank=True, null=True)),
                ('kuryer_id', models.BigIntegerField()),
                ('kuryer_name', models.CharField(max_length=55)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.TextField(blank=True, null=True)),
                ('cash_operation', models.TextField()),
                ('cash_message', models.CharField(blank=True, max_length=255)),
                ('grated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menedjer kassa',
                'verbose_name_plural': 'Menedjer kassa yozувлари',
                'db_table': 'cash_menedjer',
            },
        ),
        migrations.RemoveField(
            model_name='cashboss',
            name='business',
        ),
        migrations.RemoveIndex(
            model_name='cashstate',
            name='cash_state_busines_89fbd4_idx',
        ),
        migrations.RenameField(
            model_name='cashstate',
            old_name='boss_id',
            new_name='menedjer_id',
        ),
        migrations.RenameField(
            model_name='cashstate',
            old_name='boss_name',
            new_name='menedjer_name',
        ),
        migrations.AddField(
            model_name='cashmenedjer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='cashstate',
            name='cash_boss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_state', to='finance.cashmenedjer'),
        ),
        migrations.AddIndex(
            model_name='cashstate',
            index=models.Index(fields=['business', 'menedjer_id', 'status'], name='cash_state_busines_8144f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmenedjer',
            index=models.Index(fields=['business', 'menedjer_id'], name='idx_cash_menedjer_mgr'),
        ),
        migrations.AddIndex(
            model_name='cashmenedjer',
            index=models.Index(fields=['business', 'kuryer_id'], name='idx_cash_menedjer_kur'),
        ),
        migrations.DeleteModel(
            name='CashBoss',
        ),
    ]
