# Generated by Django 5.2.4 on 2025-09-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermenedjer_delete_userboss_and_more'),
        ('finance', '0009_cashmenedjer_remove_cashboss_business_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courierwaterbottlebalance',
            name='idx_kwbb_boss',
        ),
        migrations.RenameField(
            model_name='courierwaterbottlebalance',
            old_name='boss_id',
            new_name='menedjer_id',
        ),
        migrations.RenameField(
            model_name='courierwaterbottlebalance',
            old_name='boss_name',
            new_name='menedjer_name',
        ),
        migrations.AddIndex(
            model_name='courierwaterbottlebalance',
            index=models.Index(fields=['business', 'menedjer_id'], name='idx_kwbb_menedjer'),
        ),
    ]
