# Generated by Django 5.2.4 on 2025-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermenedjer_delete_userboss_and_more'),
        ('finance', '0010_remove_courierwaterbottlebalance_idx_kwbb_boss_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cashkuryer',
            name='idx_ck_boss',
        ),
        migrations.RemoveIndex(
            model_name='cashkuryer',
            name='idx_ck_kuryer',
        ),
        migrations.RenameField(
            model_name='cashkuryer',
            old_name='boss_id',
            new_name='menedjer_id',
        ),
        migrations.RenameField(
            model_name='cashkuryer',
            old_name='boss_name',
            new_name='menedjer_name',
        ),
        migrations.AlterField(
            model_name='cashkuryer',
            name='buyurtma_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashkuryer',
            name='cash_operation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cashkuryer',
            name='client_tel_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashkuryer',
            name='client_tg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashkuryer',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cashkuryer',
            index=models.Index(fields=['business', 'menedjer_id'], name='idx_ck_mgr'),
        ),
        migrations.AddIndex(
            model_name='cashkuryer',
            index=models.Index(fields=['business', 'kuryer_id'], name='idx_ck_kuryer'),
        ),
    ]
