# Generated by Django 5.2.4 on 2025-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermenedjer_delete_userboss_and_more'),
        ('finance', '0011_remove_cashkuryer_idx_ck_boss_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssystemaccount',
            options={'verbose_name': 'Бизнес тизим ҳисоби', 'verbose_name_plural': 'Бизнес тизим ҳисоби'},
        ),
        migrations.RenameField(
            model_name='businesssystemaccount',
            old_name='balance',
            new_name='tizimdagi_balance',
        ),
        migrations.RenameIndex(
            model_name='businesssystemaccount',
            new_name='idx_bsa_op',
            old_name='idx_bsa_biz_op',
        ),
        migrations.RemoveField(
            model_name='businesssystemaccount',
            name='note',
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='buyurtma_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='client_tg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='kuryer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='kuryer_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='menedjer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='menedjer_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemaccount',
            name='tulov_tizimi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesssystemaccount',
            name='operation',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='businesssystemaccount',
            index=models.Index(fields=['business', 'menedjer_id'], name='idx_bsa_mgr'),
        ),
        migrations.AddIndex(
            model_name='businesssystemaccount',
            index=models.Index(fields=['business', 'kuryer_id'], name='idx_bsa_kur'),
        ),
        migrations.AddIndex(
            model_name='businesssystemaccount',
            index=models.Index(fields=['business', 'status'], name='idx_bsa_status'),
        ),
    ]
