# Generated by Django 5.2.4 on 2025-09-19 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_businesssystemaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=50)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('id_tg_client', models.BigIntegerField(blank=True, null=True)),
                ('tel_num_client', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'), models.Index(fields=['order_id'], name='transaction_order_i_c4ecd3_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
            },
        ),
    ]
