# Generated by Django 5.2.5 on 2025-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_userboss_boss_tel_num_user_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboss',
            options={'verbose_name': 'Boss', 'verbose_name_plural': 'Босс турдаги фойдаланувчилар'},
        ),
    ]
