# Generated by Django 5.2.5 on 2025-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userboss_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userboss',
            old_name='promkod',
            new_name='agent_promkod',
        ),
        migrations.AddField(
            model_name='userboss',
            name='agent_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='userboss',
            name='lang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
