# Generated by Django 5.2.5 on 2025-09-05 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_promkod_userboss_agent_promkod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Бизнесс эгаси турдаги фойдаланувчилар'},
        ),
        migrations.AddField(
            model_name='business',
            name='agent_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='agent_promkod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='grated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='link_tg_group',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='narxlar_diap_davri',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=8),
        ),
        migrations.AddField(
            model_name='business',
            name='oy_bosh_sotil_suv_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='service_price_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='shaxar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tg_token',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tuman',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='viloyat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='yil_bosh_sotil_suv_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userboss',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boss_users', to='accounts.business'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['narxlar_diap_davri'], name='idx_business_diap_davr'),
        ),
        migrations.AlterModelTable(
            name='business',
            table='accounts_business',
        ),
    ]
