# Generated by Django 5.2.5 on 2025-09-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_options_business_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userboss',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='agent_promkod',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='kuryer_id',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='link_tg_group',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='shahar',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='tg_token',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='tuman',
        ),
        migrations.RemoveField(
            model_name='userboss',
            name='viloyat',
        ),
    ]
