# Generated by Django 5.2.4 on 2025-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userboss_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Бизнеслар'},
        ),
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='pin_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='link_tg_group',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='tg_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['tg_token'], name='idx_business_tg_token'),
        ),
    ]
