# Generated by Django 5.2.4 on 2025-09-11 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_business_options_business_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenedjer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('menedjer_id', models.BigIntegerField(unique=True)),
                ('menedjer_name', models.CharField(max_length=55)),
                ('boss_tel_num', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=8, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menedjer_users', to='accounts.business')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menedjer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menedjer',
                'verbose_name_plural': 'Menedjerlar',
                'db_table': 'user_menedjer',
            },
        ),
        migrations.DeleteModel(
            name='UserBoss',
        ),
        migrations.AddIndex(
            model_name='usermenedjer',
            index=models.Index(fields=['menedjer_id'], name='idx_usermenedjer_menedjerid'),
        ),
    ]
