# Generated by Django 5.2.4 on 2025-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermenedjer_delete_userboss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(db_index=True, max_length=80)),
                ('shaxar_yoki_tuman_nomi', models.CharField(db_index=True, max_length=120)),
                ('shaxar_yoki_tuman', models.CharField(choices=[('шаҳар', 'шаҳар'), ('туман', 'туман')], db_index=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Гео (шаҳар/туман)',
                'verbose_name_plural': 'Гео (шаҳар/туман)',
                'db_table': 'geo_list',
                'indexes': [models.Index(fields=['viloyat', 'shaxar_yoki_tuman', 'shaxar_yoki_tuman_nomi'], name='idx_geo_vil_tur_nomi')],
                'constraints': [models.UniqueConstraint(fields=('viloyat', 'shaxar_yoki_tuman_nomi', 'shaxar_yoki_tuman'), name='uq_geo_viloyat_nomi_turi')],
            },
        ),
    ]
