# Generated by Django 5.2.5 on 2025-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_geo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='boss_tel_num',
            field=models.CharField(blank=True, db_column='boss_tel_num', max_length=15, null=True),
        ),
    ]
