# Generated by Django 5.2.5 on 2025-09-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_business_boss_tel_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='grated',
        ),
    ]
