# Generated by Django 5.2.5 on 2025-09-12 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_business_grated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='narxlar_diap_davri',
            field=models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='oy_bosh_sotil_suv_soni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='sana',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='service_price_rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='yil_bosh_sotil_suv_soni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
