# Generated by Django 5.2.5 on 2025-09-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_business_narxlar_diap_davri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek (Cyrillic)'), ('uz_lat', 'Uzbek (Latin)'), ('ru', 'Русский'), ('en', 'English')], db_index=True, default='uz', max_length=10),
        ),
    ]
