# Generated by Django 5.2.5 on 2025-09-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_business_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('actor_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('login_success', 'Кириш муваффақиятли'), ('login_fail', 'Кириш муваффақиятсиз'), ('reg_ok', 'Рўйхатдан ўтди'), ('reg_already', 'Аллақачон рўйхатдан ўтган'), ('fp_start', 'Паролни тиклаш коди юборилди'), ('fp_verify_ok', 'Код тасдиқланди'), ('fp_verify_fail', 'Код тасдиқланмади')], db_index=True, max_length=40)),
                ('path', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=8)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=30)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-ts'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'managed': False, 'verbose_name_plural': 'Бизнеслар'},
        ),
    ]
