# Generated by Django 5.2.4 on 2025-09-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auditlog_alter_business_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolist',
            options={'managed': False, 'verbose_name': 'Гео (шаҳар/туман)', 'verbose_name_plural': 'Гео (шаҳар/туман)'},
        ),
    ]
