# Generated by Django 5.2.5 on 2025-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuryer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sana', models.DateField()),
                ('kuryer_id', models.BigIntegerField(unique=True)),
                ('kuryer_name', models.CharField(max_length=55)),
                ('avto_num', models.TextField(blank=True, null=True)),
                ('avto_marka', models.TextField(blank=True, null=True)),
                ('tel_num', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=8, null=True)),
                ('grated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlar',
                'db_table': 'kuryer',
                'indexes': [models.Index(fields=['kuryer_id'], name='idx_kuryer_id'), models.Index(fields=['tel_num'], name='idx_kuryer_tel')],
            },
        ),
    ]
