# Generated by Django 5.2.5 on 2025-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuryer',
            options={'verbose_name': 'Курерлар', 'verbose_name_plural': 'Курерлар'},
        ),
    ]
