# Generated by Django 5.2.4 on 2025-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_alter_kuryer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuryer',
            options={'verbose_name': 'Kuryer', 'verbose_name_plural': 'Kuryerlar'},
        ),
        migrations.AddField(
            model_name='kuryer',
            name='bottle_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
