# Generated by Django 5.2.4 on 2025-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_alter_kuryer_options_kuryer_bottle_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuryer',
            name='bottle_balance',
        ),
        migrations.AddField(
            model_name='kuryer',
            name='lang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
