# Generated by Django 5.2.4 on 2025-09-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_remove_kuryer_bottle_balance_kuryer_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuryer',
            name='service_price_rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
