# Generated by Django 5.2.4 on 2025-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_kuryer_service_price_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuryer',
            name='narxlar_diap_davri',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=8),
        ),
        migrations.AddField(
            model_name='kuryer',
            name='oy_bosh_sotil_suv_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kuryer',
            name='yil_bosh_sotil_suv_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='kuryer',
            index=models.Index(fields=['narxlar_diap_davri'], name='idx_kuryer_diap_davr'),
        ),
    ]
