# Generated by Django 5.2.5 on 2025-09-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_options_business_agent_name_and_more'),
        ('couriers', '0006_kuryer_narxlar_diap_davri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuryer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='couriers', to='accounts.business'),
        ),
        migrations.AddIndex(
            model_name='kuryer',
            index=models.Index(fields=['business'], name='idx_kuryer_business'),
        ),
    ]
