# Generated by Django 5.2.5 on 2025-09-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0007_kuryer_business_kuryer_idx_kuryer_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuryer',
            options={'verbose_name': 'Kuryer', 'verbose_name_plural': 'Курерлар'},
        ),
    ]
