# Generated by Django 5.2.5 on 2025-09-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_business_userboss_boss_tel_num_user_business'),
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('client_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('client_tel_num', models.CharField(max_length=15)),
                ('suv_soni', models.PositiveIntegerField()),
                ('manzil', models.TextField()),
                ('buyurtma_statusi', models.CharField(choices=[('pending', 'Кутилмоқда'), ('assigned', 'Бириктирилди'), ('accepted', 'Қабул қилинди'), ('on_way', 'Йўлда'), ('delivered', 'Топширилди'), ('failed', 'Бажарилмади'), ('cancelled', 'Бекор қилинди')], default='pending', max_length=12)),
                ('pay_status', models.CharField(choices=[('none', 'Йўқ'), ('cash', 'Нақд'), ('online', 'Онлайн')], default='none', max_length=8)),
                ('kuryer_ext_id', models.BigIntegerField(blank=True, null=True)),
                ('kuryer_name', models.CharField(blank=True, max_length=55, null=True)),
                ('kuryer_tel_num', models.CharField(blank=True, max_length=15, null=True)),
                ('sotilgan_tara_soni', models.PositiveIntegerField(default=0)),
                ('yil_bosh_sotil_suv_soni', models.PositiveIntegerField(default=0)),
                ('oy_bosh_sotil_suv_soni', models.PositiveIntegerField(default=0)),
                ('qullanilgan_akciya', models.TextField(blank=True, null=True)),
                ('grated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
                ('kuryer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyurtmalar', to='couriers.kuryer')),
            ],
            options={
                'db_table': 'buyurtmalar',
                'indexes': [models.Index(fields=['business', 'sana'], name='idx_buyurtma_biz_sana'), models.Index(fields=['business', 'buyurtma_statusi'], name='idx_buyurtma_biz_status'), models.Index(fields=['business', 'client_tel_num'], name='idx_buyurtma_biz_client_tel')],
            },
        ),
    ]
