# Generated by Django 5.2.4 on 2025-09-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_buyurtma_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='pay_status',
            field=models.CharField(choices=[('none', 'Йўқ'), ('pend_pay', 'Кутилмоқда'), ('cash', 'Нақд'), ('online', 'Онлайн')], default='none', max_length=8),
        ),
    ]
