# Generated by Django 5.2.5 on 2025-09-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_buyurtma_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='kuryer_ext_id',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='location_accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='location_source',
            field=models.CharField(choices=[('tg', 'telegram'), ('geocode', 'geocode'), ('manual', 'manual')], default='manual', max_length=16),
        ),
    ]
