# Generated by Django 5.2.5 on 2025-09-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_buyurtma_kuryer_ext_id_buyurtma_lat_and_more'),
    ]

    operations = [
    ]
