# Generated by Django 5.2.4 on 2025-09-18 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_normalize_buyurtmalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='manzil_izoh',
            field=models.TextField(blank=True, help_text='Буюртмачи хонадонини топиш учун қисқа изоҳ', null=True),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='location_accuracy',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
