# Generated by Django 5.2.4 on 2025-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_buyurtma_manzil_izoh_alter_buyurtma_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='qullanilgan_akciya',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='order_num',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
