# Generated by Django 5.2.4 on 2025-09-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_buyurtma_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='pay_status',
            field=models.CharField(choices=[('none', 'Йўқ'), ('waiting_for_payment', 'Онлайн тўлаш кутилмоқда'), ('pending', 'Онлайн жараёнда'), ('completed_online', 'Онлайн тўланди'), ('cash', 'Нақд')], default='none', max_length=55),
        ),
    ]
