# Generated by Django 5.2.4 on 2025-09-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_buyurtma_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
