# Generated by Django 5.2.4 on 2025-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_buyurtma_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='buyurtma_statusi',
            field=models.CharField(choices=[('pending', 'Кутилмоқда'), ('assigned', 'Бириктирилди'), ('on_way', 'Йўлда'), ('delivered', 'Топширилди'), ('failed', 'Бажарилмади'), ('cancelled', 'Бекор қилинди')], default='pending', max_length=12),
        ),
    ]
